Update claudia.overlay
Error message:
ValueError: invalid literal for int() with base 8: '09'

09 seems acceptable, suggesting change to 01 for testing